### ISSUE TITLE
如何二次代理

### ISSUE THREAD

**Issue by fengsweat** [Meituan-Dianping/lyrebird#103]
你好,假如 app的api是需要翻墙访问的, 我将MAC机 安装了lyrebird , 然后MAC机使用SS 全局翻墙, app api 无法正常访问,请问lyrebird如何配置二次代理.

**Comment by zhaoye** [comment]
**你好，Lyrebird目前不支持设置代理。**

**但是，我觉得有其他的解决方案：**
你看是不是这样 @fengsweat 
1.你之前的情况:
client --> proxy --> API server
2.使用Lyrebird无法访问的情况：
client --> lyrebird --> API server
3.期望的用法
client --> lyrebird --> proxy --> API server
这里，由于Lyrebird不支持设置代理，而无法实现

4.替代方案
client ---[通过直连而不是代理将请求发到Lyrebird]--> lyrebird --[此处使用系统代理或iptable，使Lyrebird发出的请求走原先ss ]--> proxy --> API server

**Comment by zhaoye** [comment]
直连的方式需要client发出请求的部分作出修改，即 由http://your-api-host/path 改成 http://lyrebird-host/mock/http://your-api-host/path
