### ISSUE TITLE
Record提示可以优化下

### ISSUE THREAD

**Issue by myth0506** [Meituan-Dianping/lyrebird#104]
页面左上角点红色和黑色录制按钮鼠标放上去都是Record提示，看是否可以优化下，在不同情况下显示不同都提示

**Comment by myth0506** [comment]
<img width="1439" alt="28" src="https://user-images.githubusercontent.com/16068502/52771739-a6d62300-3071-11e9-9d8d-22fcd41f8e16.png">

**Comment by zhaoye** [comment]
确认是问题
