### ISSUE TITLE
lyrebird后台报错

### ISSUE THREAD

**Issue by levey1105** [Meituan-Dianping/lyrebird#127]
**Describe the bug**
启动lyrebird后，正常使用APP，lyrebird后台报错
**To Reproduce**
1. 启动lyrebird
2. 操作手机连接上代理
3. 正常操作APP
4. 实际结果：lyrebird后台报错

**Screenshots**
![image](https://user-images.githubusercontent.com/47141083/54799108-b3fcb800-4c96-11e9-8d13-2ff27bcd7a94.png)

**Desktop (please complete the following information):**
 - Version 1.5.0

**Comment by zhaoye** [comment]
Fixed #133
