### ISSUE TITLE
lyrebrid 日志中报错

### ISSUE THREAD

**Issue by Pearlsum** [Meituan-Dianping/lyrebird#139]
**Describe the bug**
启动lyrebird后，正常使用APP，lyrebird后台报错

**To Reproduce**
1.启动lyrebird
2.操作手机连接上代理
3.正常操作APP
4.实际结果：lyrebird后台报错

**Screenshots**
![image](https://user-images.githubusercontent.com/12393836/55706994-171b7800-5a15-11e9-81e6-1ea891f69131.png)

**Additional context**
lyrebrid version 1.6.3

**Comment by zhaoye** [comment]
Fixed
