### ISSUE TITLE
lyrebird可以用来测试埋点么？

### ISSUE THREAD

**Issue by meihaoyidian** [Meituan-Dianping/lyrebird#145]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhaoye** [comment]
可以的。
可以通过插件 https://github.com/Meituan-Dianping/lyrebird-tracking 实现。
也可以针对埋点开发自己的[检查脚本](https://meituan-dianping.github.io/lyrebird/checker/)

@meihaoyidian
