### ISSUE TITLE
在浏览器中如何查看页面的地址，直接使用本机ip:4272,400 Bad Request

### ISSUE THREAD

**Issue by martin-huang** [Meituan-Dianping/lyrebird#168]
我这边也是，安装后没有打开 4272 。自己打开4272 的时候是400错误 打开9090 是500错误

**Comment by martin-huang** [comment]
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by zhaoye** [comment]
https://pypi.org/project/lyrebird/
已在lyrebird v1.6.13修复此问题。

@martin-huang
