### ISSUE TITLE
Mock 数据自动升级后，原有的数据继承关系丢失

### ISSUE THREAD

**Issue by reeyur** [Meituan-Dianping/lyrebird#230]
**Describe the bug**
v1.6.x 版本 Lyrebird 生成带有继承关系的 Mock 数据，使用 v1.7.x 版本升级后，继承关系丢失

**To Reproduce**
1. v1.6.x 录制一份带有继承关系的 Mock 数据
2. 升级 Lyrebird 至 v1.7.x
3. 激活升级后的 Mock 数据查看继承关系

**Expected behavior**
Mock 数据继承关系保留

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrom
 - Version 22

**Comment by zhaoye** [comment]
Fixed in #239
