### ISSUE TITLE
checker 支持分组

### ISSUE THREAD

**Issue by PearlSumRise** [Meituan-Dianping/lyrebird#269]
**Describe the feature**
Checker Scripts支持分组：

1.分组主要分为2大类：通用和特定方向分组（脚本越来越多，方便区分）
2.启动lyrebrid后（lb start 方向），开启通用分组所有默认打开的脚本，同时根据启动lyrebird 时的方向，开启该方向所有默认打开的脚本（每个Checker 脚本有2个属性：分组（通用、特定方向）、是否默认开启）

**Comment by zhaoye** [comment]
已实现 @PearlSumRise
