### ISSUE TITLE
相同的接口，不同的mock结果，只会触发列表的第一条

### ISSUE THREAD

**Issue by youngfreeFJS** [Meituan-Dianping/lyrebird#292]
操作步骤：
1、在datamanger根目录下创建【group1】
2、在【group1】下保存接口【/api/test1】【/api/test1】，并激活
3、修改第一个【/api/test1】的 responseData 为：1000
4、修改第二个【/api/test1】的 responseData 为：2000

遇到问题：
mock【/api/test1】永远只会触发1000，而不会触发2000的结果

**Comment by zhaoye** [comment]
两个接口命中条件冲突。

**Comment by mijiawei** [comment]
> 两个接口命中条件冲突。

同名接口如何配置根据入参不同返回不同mock数据？

**Comment by zhaoye** [comment]
> > 两个接口命中条件冲突。
> 
> 同名接口如何配置根据入参不同返回不同mock数据？

@mijiawei 

```JSON
"rule": {
        "request.url": "(?=.*/pathxxx)(?=*arg1)(?=*arg2)"
    }
```
