### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by liuwei12931902** [Meituan-Dianping/lyrebird#341]
Get devices list error/bin/sh: /usr/local/share/android-sdk/platform-tools/adb: No such file or directory

**Comment by zhaoye** [comment]
Lyrebird find adb by ANDROID_HOME env
Please make sure  $ANDROID_HOME/platform-tools/adb is exists
@liuwei12931902

**Comment by zhaoye** [comment]
Fixed
