### ISSUE TITLE
依赖的pillow版本不支持python3.9，请问可以兼容吗？谢谢

### ISSUE THREAD

**Issue by allen-shen** [Meituan-Dianping/lyrebird#426]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhaoye** [comment]
虽然已经关了。。。 py3.9目前暂不支持，除pillow外还有很多需要适配的内容。

**Comment by zhaoye** [comment]
python3.9现已支持
