### ISSUE TITLE
Android手机连不上

### ISSUE THREAD

**Issue by BlainPeng** [Meituan-Dianping/lyrebird#428]
按照[官方文档](https://meituan-dianping.github.io/lyrebird/guide/#%E5%AE%89%E8%A3%85)操作，UI界面已在浏览器成功打开。但是按照步骤连接Android设备时，在手机端打开[http://mitm.it](http://mitm.it)时手机界面一直显示连接错误，手机无法连上网络。不知道咋回事。8.0系统华为手机和10.0系统小米手机都不行。

**Comment by zhaoye** [comment]
我们先来检查一下链接是否正常：
```python
+----------+                         +-----------+
+ Lyrebird + ------  (WiFi)  --------+  手机      +
+----------+                         +-----------+
```
如上图,测试手机是否能访问Lyrebird所在设备。
在手机浏览器删输入Lyrebird设备的地址及端口。
例如：http://192.168.10.2:9090  (具体IP按实际情况填写)
如果网络连通，则可以在手机浏览器上使用Lyrebird前端。如果不能访问说明连通有问题。请检查你的WiFi等相关设置。
@BlainPeng

**Comment by BlainPeng** [comment]
昨天刚开始是在公司内网没有操作成功。回去后，确实成功了。在手机浏览器输入Lyrebird的地址也成功了，浏览器网络请求的日志也抓到了。但是在抓APP的请求还是抓不到。如打开抖音时界面都是提示网络连接异常。我用自己公司的app抓登录请求日志连不上网络。

**Comment by woods-dev** [comment]
这个问题，所有捉包工具对安卓无解，用苹果吧。

**Comment by zhaoye** [comment]
如果还是HTTP协议的话，一般来说会有两个机制来保护数据不被篡改:
1. 通过HTTPS保护数据
    > 这种情况比较适用于中间人代理，通过代理服务替换HTTPS证书，实现抓包
2. 客户端对HTTPS证书验证
    > 为了保护客户端不被中间人攻击，客户端会对证书进行验证。发现非法证书会主动断开连接。

**这就要求测试自己公司APP时，有一定的可测性支持。**
> 比如可选择使用HTTP服务或者可以关闭证书验证等，使得测试活动可以正常进行。

希望可以帮到你
@BlainPeng

**Comment by BlainPeng** [comment]
> 如果还是HTTP协议的话，一般来说会有两个机制来保护数据不被篡改:
> 
> 1. 通过HTTPS保护数据
>    > 这种情况比较适用于中间人代理，通过代理服务替换HTTPS证书，实现抓包
> 2. 客户端对HTTPS证书验证
>    > 为了保护客户端不被中间人攻击，客户端会对证书进行验证。发现非法证书会主动断开连接。
> 
> **这就要求测试自己公司APP时，有一定的可测性支持。**
> 
> > 比如可选择使用HTTP服务或者可以关闭证书验证等，使得测试活动可以正常进行。
> 
> 希望可以帮到你
> @BlainPeng

好的。谢谢！
