### ISSUE TITLE
使用lyrebird代理访问https://m.trc.com，显示空白页

### ISSUE THREAD

**Issue by nancyhu1229** [Meituan-Dianping/lyrebird#43]
iOS手机上访问网址 https://m.trc.com ，期望能正常打开，实际显示空白页。

已尝试的方案：
1、桌面版mitmproxy(exe安装包）可以正常访问 该网站
2、mitmdump -s addons.py命令启动自己编写addons.py , 也可以正常访问 该网址
3、windows 和 mac  都出现如上同样问题

调试现象：
访问该地址，请求没有进入 api_mock.py接口内。

**Comment by zhaoye** [comment]
处理中

**Comment by zhaoye** [comment]
已修复 @nancyhu1229 

![image](https://user-images.githubusercontent.com/4516926/54337378-b4c79580-4669-11e9-8117-a7aeaad611e0.png)
