### ISSUE TITLE
有没有详细一些的使用文档？

### ISSUE THREAD

**Issue by ShaoBing2017** [Meituan-Dianping/lyrebird#44]
看了开发者大会上的文档，感觉高大上的一个工具！但是，不会用。自己研究了一下，还是不会用！
所以还请描述一下如何使用.Thanks!

**Comment by ShaoBing2017** [comment]
> 十分感谢您的支持。
> 确实文档这部分比较少。 因为现在开源的部分还不是完整的Lyrebird。
> 我们会在11月完成这个部分并完成文档。包括使用及开发手册。

非常期待完整版的Lyrebird以及使用文档！

**Comment by myth0506** [comment]
同样期待完善的文档。

**Comment by zhaoye** [comment]
https://meituan-dianping.github.io/lyrebird/ 文档陆续完善中，已增加新功能‘检查器’(Checker)相关文档。
@ShaoBing2017 @myth0506

**Comment by zhaoye** [comment]
https://meituan-dianping.github.io/lyrebird/
@ShaoBing2017 随v1.7.0更新文档

**Comment by ShaoBing2017** [comment]
非常感谢！
工具很好，先研究一把怎么玩 ：）
________________________________
发件人: zhaoye <notifications@github.com>
发送时间: 2019年9月5日 19:24
收件人: Meituan-Dianping/lyrebird <lyrebird@noreply.github.com>
抄送: ShaoBing2017 <shaobing1983@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [Meituan-Dianping/lyrebird] 有没有详细一些的使用文档？ (#44)


https://meituan-dianping.github.io/lyrebird/
@ShaoBing2017<https://github.com/ShaoBing2017> 随v1.7.0更新文档

―
