### ISSUE TITLE
更新到最新版本提示 no moudle nameed    "mitmproxy.tools.main"

### ISSUE THREAD

**Issue by mayaaihaozhe** [Meituan-Dianping/lyrebird#463]
pthon version: python3.7、python3.9.1
启动方式：命令行启动
安装方式：pip3 install   lyrbird

**Comment by zhaoye** [comment]
请问是怎么启动的呢 ？ @mayaaihaozhe

**Comment by mayaaihaozhe** [comment]
启动命令：lyrebird  -v   -v
提示错误日志：
raceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lyrebird/proxy/mitm_exec.py", line 3, in <module>
    from mitmproxy.tools.main import mitmdump
ImportError: No module named mitmproxy.tools.main

**Comment by mutour** [comment]
我也遇到同样问题， Python 3.8.2
```
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/lyrebird/proxy/mitm_exec.py", line 3, in <module>
    from mitmproxy.tools.main import mitmdump
ImportError: No module named mitmproxy.tools.main
```

**Comment by zhaoye** [comment]
修复中

**Comment by zhaoye** [comment]
Fixed in #465

**Comment by zhaoye** [comment]
已在1.19.1修复
@mayaaihaozhe @mutour
