### ISSUE TITLE
1.19.1运行提示{"hello":"clash"}

### ISSUE THREAD

**Issue by mutour** [Meituan-Dianping/lyrebird#466]
安装1.19.0版本,提示以下错误
```
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/lyrebird/proxy/mitm_exec.py", line 3, in <module>
    from mitmproxy.tools.main import mitmdump
ImportError: No module named mitmproxy.tools.main
```

升级到1.19.1版本后, 上面的问题不存在了
但是仍然无法是使用

使用lyrebird -v运行后:
```
NOTICE [manager]

     _                    _     _         _
    | |                  | |   (_)       | |
    | |    _   _ _ __ ___| |__  _ _ __ __| |
    | |   | | | | '__/ _ \ '_ \| | '__/ _' |
    | |___| |_| | | |  __/ |_) | | | | (_| |
    \_____/\__, |_|  \___|_.__/|_|_|  \__,_|
            __/ |
           |___/

                   v1.19.1



WARNING [manager] Lyrebird start with config:
{
    "version": "0.10.5",
    "proxy.filters": [],
    "proxy.port": 4272,
    "mock.port": 9090,
    "mock.data": "/Users/xxxxx/.lyrebird/mock_data/personal",
    "mock.proxy_headers": {
        "scheme": "MKScheme",
        "host": "MKOriginHost",
        "port": "MKOriginPort"
    },
    "ip": "192.168.8.156",
    "verbose": 1
}
WARNING [proxy_server] start on http://192.168.8.156:4272    ***请在被测设备上设置代理服务器地址***
WARNING [mock_server] start on http://192.168.8.156:9090
 * Serving Flask app "MOCK" (lazy loading)
 * Environment: development
 * Debug mode: off

```

浏览器打开了http://localhost:9090/
但是内容显示为  {"hello":"clash"}

使用手机访问地址http://192.168.8.156:4272
提示错误400
400 Bad Request
HttpException('Invalid HTTP request from (expected: authority or absolute, got: relative)')

何解?

**Comment by mutour** [comment]
> 安装1.19.0版本,提示以下错误
> 
> ```
> Traceback (most recent call last):
>   File "/Library/Python/3.8/site-packages/lyrebird/proxy/mitm_exec.py", line 3, in <module>
>     from mitmproxy.tools.main import mitmdump
> ImportError: No module named mitmproxy.tools.main
> ```
> 
> 升级到1.19.1版本后, 上面的问题不存在了
> 但是仍然无法是使用
> 
> 使用lyrebird -v运行后:
> 
> ```
> NOTICE [manager]
> 
>      _                    _     _         _
>     | |                  | |   (_)       | |
>     | |    _   _ _ __ ___| |__  _ _ __ __| |
>     | |   | | | | '__/ _ \ '_ \| | '__/ _' |
>     | |___| |_| | | |  __/ |_) | | | | (_| |
>     \_____/\__, |_|  \___|_.__/|_|_|  \__,_|
>             __/ |
>            |___/
> 
>                    v1.19.1
> 
> 
> 
> WARNING [manager] Lyrebird start with config:
> {
>     "version": "0.10.5",
>     "proxy.filters": [],
>     "proxy.port": 4272,
>     "mock.port": 9090,
>     "mock.data": "/Users/xxxxx/.lyrebird/mock_data/personal",
>     "mock.proxy_headers": {
>         "scheme": "MKScheme",
>         "host": "MKOriginHost",
>         "port": "MKOriginPort"
>     },
>     "ip": "192.168.8.156",
>     "verbose": 1
> }
> WARNING [proxy_server] start on http://192.168.8.156:4272    ***请在被测设备上设置代理服务器地址***
> WARNING [mock_server] start on http://192.168.8.156:9090
>  * Serving Flask app "MOCK" (lazy loading)
>  * Environment: development
>  * Debug mode: off
> ```
> 
> 浏览器打开了http://localhost:9090/
> 但是内容显示为 {"hello":"clash"}
> 
> 使用手机访问地址http://192.168.8.156:4272
> 提示错误400
> 400 Bad Request
> HttpException('Invalid HTTP request from (expected: authority or absolute, got: relative)')
> 
> 何解?

pc上访问http://192.168.8.156:9090, 可以正常访问主页, 但是手机仍然是400错误无法访问

**Comment by zhaoye** [comment]
@mutour 问题是解决了吗

**Comment by mutour** [comment]
> @mutour 问题是解决了吗

pc上访问http://192.168.8.156:9090, 可以正常访问主页.
但是：
手机设置代理后命令行使用lyrebird -v可以看到访问请求，但是主页没有任何反应，任何内容都没有

**Comment by zhaoye** [comment]
> > @mutour 问题是解决了吗
> 
> pc上访问http://192.168.8.156:9090, 可以正常访问主页.
> 但是：
> 手机设置代理后命令行使用lyrebird -v可以看到访问请求，但是主页没有任何反应，任何内容都没有

@mutour
意思是日志上显示有内容，而前端没有显示？那么刷新是不是就显示数据了呢？
我们来确认一下操作步骤：
1. 启动lyrebird `lyrebird -v`
2. 在手机上设置代理 `http://[lyrebird ip]:4272`
3. （可选）如果有https请求，则需要在手机上用浏览器打开mitm.it安装相应操作系统的证书
4. 手机上用浏览器打开 `http://[lyrebird ip]:9090` 检查是否能访问到lyrebrid
5. 如果上述步骤都正常，那么现在可以在lyrebird上查看手机发出的请求了

**Comment by evilwk** [comment]
自己开了clash代理呗，占用了9090端口，lyrebird --mock [port] 换个端口
