### ISSUE TITLE
请问一下该如何去实现修改响应的功能呢

### ISSUE THREAD

**Issue by 719123705** [Meituan-Dianping/lyrebird#468]
如题，因为抓包抓到的接口数据是加密的，想显示解密后的内容

**Comment by zhaoye** [comment]
@719123705 
可以自定义加解密逻辑，前提是你有加解密的算法或可调用对应的API
之后按照下面的方式开发脚本，在启动lyrebird时加载此脚本即可实现自动加解密

```python
from lyrebird import decoder, encoder


@decoder()
def _decode(flow):
    _data = flow['response']['data']
    # 解密方法或API
    _decoded_data = some_decode_func(_data)
    flow['response']['data'] = _decoded_data


@encoder()
def _encode(flow):
    _data = flow['response']['data']
    # 加密方法或API
    _encoded_data = some_encode_func(_data)
    flow['response']['data'] = _encoded_data
```

开发\调试说明见文档 https://meituan-dianping.github.io/lyrebird/checker/#%E8%BD%BD%E5%85%A5%E6%A3%80%E6%9F%A5%E5%99%A8

**Comment by 719123705** [comment]
> @719123705
> 可以自定义加解密逻辑，前提是你有加解密的算法或可调用对应的API
> 之后按照下面的方式开发脚本，在启动lyrebird时加载此脚本即可实现自动加解密
> 
> ```python
> from lyrebird import decoder, encoder
> 
> 
> @decoder()
> def _decode(flow):
>     _data = flow['response']['data']
>     # 解密方法或API
>     _decoded_data = some_decode_func(_data)
>     flow['response']['data'] = _decoded_data
> 
> 
> @encoder()
> def _encode(flow):
>     _data = flow['response']['data']
>     # 加密方法或API
>     _encoded_data = some_encode_func(_data)
>     flow['response']['data'] = _encoded_data
> ```
> 
> 开发\调试说明见文档 https://meituan-dianping.github.io/lyrebird/checker/#%E8%BD%BD%E5%85%A5%E6%A3%80%E6%9F%A5%E5%99%A8

谢谢大佬 ，如果我在@decoder()中对请求内容flow['request']['data']内容进行解密修改，实际的请求数据会不会被解密后再发送吗

**Comment by zhaoye** [comment]
一样的，decoder和encoder是一对特殊的实现。
要同时实现对应的encoder和decoder。 
request和response都可以在这里修改。
修改参数应该是用flow['request']['url']来修改。
@719123705
