### ISSUE TITLE
请求/mock/<string:group_id>/<string:action>会报错

### ISSUE THREAD

**Issue by xiaohengdai** [Meituan-Dianping/lyrebird#469]
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/17376841/110593291-5a109800-81b6-11eb-8dc9-aea23ba2ecd5.png">

**Comment by xiaohengdai** [comment]
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/17376841/110593744-ed49cd80-81b6-11eb-81fe-269d5bda7adc.png">

**Comment by zhaoye** [comment]
请参考 https://meituan-dianping.github.io/lyrebird/guide/api.html#%E6%BF%80%E6%B4%BBmock%E6%95%B0%E6%8D%AE%E7%BB%84
