### ISSUE TITLE
请求/api/data报错

### ISSUE THREAD

**Issue by xiaohengdai** [Meituan-Dianping/lyrebird#470]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/17376841/110594325-9ee8fe80-81b7-11eb-9985-7f0b2508d124.png">

![image](https://user-images.githubusercontent.com/17376841/110594568-ed969880-81b7-11eb-9385-c55f89811e54.png)

**Comment by zhaoye** [comment]
get 请求必须指明ID
