### ISSUE TITLE
from mitmproxy.tools.main import mitmdump ImportError: No module named mitmproxy.tools.main

### ISSUE THREAD

**Issue by bingyan719** [Meituan-Dianping/lyrebird#485]
**Description**
启动 lyrebird 报错

**To Reproduce**
 * Serving Flask app "MOCK" (lazy loading)
 * Environment: development
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/lyrebird/proxy/mitm_exec.py", line 3, in <module>
    from mitmproxy.tools.main import mitmdump
ImportError: No module named mitmproxy.tools.main

python版本：Python 3.8.8

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhaoye** [comment]
有几个问题请补充一下 @bingyan719 

是怎么启动的？
1. 通过源码
2. pip install之后，命令行执行lyrebird
3. 使用docker镜像

lyrebird的版本是什么？
