### ISSUE TITLE
同名接口如何配置针对request body的rule返回对应mock数据

### ISSUE THREAD

**Issue by mijiawei** [Meituan-Dianping/lyrebird#509]
**Description**
At infomation config
{
    "id": "5f0a0871-fc3b-466d-aa91-0f5da4fb924f",
    "name": "/copy/all",
    "rule": {
        "request.url": "(?=.*/copy/all)"
    }
}
such as request: {"data":true ,"tick":123}
using these variables written in "rule" did not work: request.body request.body.data....

**Comment by zhaoye** [comment]
@mijiawei 

是这样的，根据数据的结构写查找路径。
```
...
"rule": {
  "request.url": "(?=.*/copy/all)",
  "request.data": ""
}
...
```
但是你举的例子里面，值是非字符串的情况目前还不支持。

-------------
另外有一种复杂一些的办法是自己构造一个[脚本](https://meituan-dianping.github.io/lyrebird/checker/request_editor.html)
在on_response回调中动态的返回数据
