### ISSUE TITLE
激活mock后，会自动保存所有请求数据至datamanager

### ISSUE THREAD

**Issue by luoyehuakai** [Meituan-Dianping/lyrebird#531]
**Description**
在抓包界面激活mock后，会自动保存所有请求至datamanager

**To Reproduce**
1.在datamanager创建group
2.在inspector激活group
3.操作手机，并查看group

**Expected behavior**
---->为主动选择保存的情况下，默认保存了所有的请求

lyrebird为最新版本

**Comment by zhaoye** [comment]
> > 是不是开启了自动保存？
> > @luoyehuakai
> 
> 这个开关不是是否开启抓包的开关么?

嗯，抓包这个事情没有开关。这个是指是不是自动保存到DataManager ，也就是你见到的现象。
很久以前的功能了，现在看起来确实没什么大用了。😂
@luoyehuakai
