### ISSUE TITLE
lyrebird抓包是遇到302的请求，无法正常跳转

### ISSUE THREAD

**Issue by yongjie6** [Meituan-Dianping/lyrebird#542]
**Description**
lyrebird抓包时，遇到302的请求，无法跳转到下一页面
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37992402/136732968-9a66f593-de5d-4c7f-adbc-db724aeb2274.png)
![image](https://user-images.githubusercontent.com/37992402/136733158-4152ca77-12e1-4ab6-84e9-d441853f4898.png)

**Desktop (please complete the following information):**
 - OS: ios

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhaoye** [comment]
> @zhaoye @yumiguan 不过我不太确定打开这个会对这个程序有啥影响么

处理重定向应该是client自己的行为，如果在代理处实现，会丢掉一些细节。 
另外如果你是在执行测试的话，建议检查一下被测对象是否有相关缺陷。
@yongjie6

**Comment by sialais** [comment]
I have encountered the same problem. I found the location in 302 response will be modified, and localhost host is added, then the url followed is not correct.
here's my screen shot, with lyrebird v1.24.1
![image](https://user-images.githubusercontent.com/41794887/141059993-7a0a974a-1b7b-47d5-bcee-094da522a460.png)
