### ISSUE TITLE
error when start lyrebird

### ISSUE THREAD

**Issue by zhao-haha** [Meituan-Dianping/lyrebird#551]
**Description**
I get error when start lyrebird with `lyrebird -v`, and then after set proxy on my iphone, i cannot open [http://mitm.it](url) either.

**Screenshots**
![image](https://user-images.githubusercontent.com/9448146/142804899-9eb38e26-a601-4a2f-be71-659cfc72e9ae.png)

**Desktop (please complete the following information):**
Mac OS 11.3
Python3.9

**Smartphone (please complete the following information):**
iphone 11
iOS 14.8

**Comment by zhaoye** [comment]
First of all ，pls make sure that on your phone can open "http://10.38.136.55:9090" with browser.
@zhao-haha
