### ISSUE TITLE
超过16位整数，response解析出错；举例：mock

### ISSUE THREAD

**Issue by tester-king** [Meituan-Dianping/lyrebird#555]
**Description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhaoye** [comment]
麻烦写详细一些吧。 @tester-king

**Comment by zhaoye** [comment]
3个月以上没有更新更多信息。无法处理该问题。
