### ISSUE TITLE
在自动化测试中使用mock功能 有这方面的文档吗

### ISSUE THREAD

**Issue by jiangweiqing** [Meituan-Dianping/lyrebird#638]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/13581539/163364277-c5a4d8a7-e9c4-4384-86e5-2c0d4938ef96.png">
有没有在自动化测试中mock 的相关的文档呀

**Comment by xiaohengdai** [comment]
文档中有的，https://meituan-dianping.github.io/lyrebird/guide/api.html#激活mock数据组
