### ISSUE TITLE
Provide a usage document 提供一份使用文档

### ISSUE THREAD

**Issue by ASkyFullOfStar** [Meituan-Dianping/lyrebird#676]
Can I have an official document like mitmproxy or Charles?
I hope to produce a user manual and a developer manual.
-------------------------------------------------------------------
请问能不能出一份类似于mitmproxy 或者 charles那样的官方文档呢？
希望出一份用户使用手册、以及一份开发者手册。

**Comment by zhaoye** [comment]
可以看一下这里 https://meituan-dianping.github.io/lyrebird/
@ASkyFullOfStar
