### ISSUE TITLE
win11 python3.7  pip下载lyrebird 报错

### ISSUE THREAD

**Issue by yiqingkuang** [Meituan-Dianping/lyrebird#699]
报错信息：
![image](https://user-images.githubusercontent.com/31410071/200209005-3f4e3f84-e4c8-4ad1-83e5-a22cf0f76093.png)

提示说下载包缺少一个requirements文件，不知道如何解决，求助

**Comment by yiqingkuang** [comment]
下载的包版本是2.10.0

**Comment by yiqingkuang** [comment]
将包回退到2.6.0 就可以正常使用

**Comment by zhaoye** [comment]
Fixed #701 
打包的地方有问题，修复中 @yiqingkuang

**Comment by zhaoye** [comment]
已在2.10.1修复此问题
