### ISSUE TITLE
mitmproxy　也是支持win或mac下代理的么？

### ISSUE THREAD

**Issue by Archer456** [Meituan-Dianping/lyrebird#7]
我是想，这个mitmproxy　可以支持部署到window10　或mac　系统硬件下的么（不是手机ios　android　wp这种系统设备下）？

部署后，可以支持代理捕获　windows或mac下　客户端程序的请求么？

如果　支持　该怎么配置　　配置后lyrebird界面是否可以正常操作

**Comment by Archer456** [comment]
https://docs.mitmproxy.org/stable/concepts-certificates/

好像　可以的？

**Comment by zhaoye** [comment]
mitmproxy的话是可以的。
你可以尝试一下在PC的网络连接中设置代理来获取数据。两个PC之间的通讯同使用手机的场景。
但是在同一个PC上启动Lyrebird，并且获取这个设备上的网络请求，这个场景我不是很确定。
十分抱歉，这部分我们还没有涉及。

**Comment by Archer456** [comment]
谢谢　指导。
１　如果有精力的话，可以试一下或支持下该方案么（测试下win10或macOS 系统下的客户端程序　同一lyrebird和pc上操作这些客户端　能否被lyrebird　正常捕获和回访使用）
２　　是否有支持　　swagger 或　postman 或har　　其他第三方比如fiddler捕获的请求　　的导入
比如httprunner提供的　转换工具　　https://github.com/HttpRunner/har2case

**Comment by Archer456** [comment]
![image](https://user-images.githubusercontent.com/18392901/42805450-6a880fd8-89de-11e8-9f20-7a4d42502a71.png)
我的想法是这样的，还是正常启动lyrebird，　然后启动该lyrebird　的pc　　访问地址http://mitm.it/　可以正常像手机设备里一样，正常的提示安装证书。　　　　然后该pc机　就挂上mitmproxy代理了。就可以正常用lyrebird操作了。

如果能这样最好。。。不知　可否支持。

**Comment by zhaoye** [comment]
对于数据导入和抓取PC端数据的支持确认可行。先标记一下。后续加入排期。
@Archer456

**Comment by Archer456** [comment]
@zhaoye   你好：
我今天在我的ubuntu18.04　尝试了下
１　只开启有线网络　且设置了内网固定ip　　（关闭无线wifi　关闭shadowsocks　排除一切其他干扰）
２　本机ubuntu启动lyrebird，找到mitmproxy代理地址和端口，
将该mitmproxy代理地址配置到　ubuntu系统里的　系统设置->网络->网络代理
３　然后用本机浏览器chrome和firefox分别访问，
firxfox　直接可以提示安装mitmproxy的证书　安装成功后　firefox浏览器打开百度测试　可抓到请求
　本机打开的网易云音乐客户端linux版的　也可抓取到请求，　chrome浏览器打开百度则无请求抓到

chrome　不可以　但我查看https://docs.mitmproxy.org/stable/concepts-certificates/　　有其它给ubutnu chrome安装证书的方法。


所以　以上证明　　本地pc机启动lyrebird的代理mitmproxy　　本地浏览器安装好证书　是可以实现对本机客户端程序（有网路请求的比如网易云音乐这种）进行代理抓取的！！！

疑问：mitmproxy　证书　是不是分为浏览器级别的　和　本机系统全局级别的。
我若想让本机系统所有的程序的网络请求都被抓取　　是不是应该参考https://docs.mitmproxy.org/stable/concepts-certificates/　　中的ubuntu　或linux　来安装全局证书？

**Comment by zhaoye** [comment]
Cool 👍 真不错。

证书的问题，我觉得参照https://docs.mitmproxy.org/stable/howto-transparent/可以实现全局信任了。
但是有些应用可能会自己进行证书校验。校验失败的话，这时候也会导致无法获取网络请求。

@Archer456

**Comment by jerry117** [comment]
我今天试了一下两台机，数据是可以抓取，但是返回的数据在被抓的机器上是不完整的，有的资源没有显示出来，例如图片？不知道是什么原因。证书我是用的地址http://mitm.it/下的window证书。
