### ISSUE TITLE
大量的http://127.0.0.1:4272/kill请求

### ISSUE THREAD

**Issue by ohyeah521** [Meituan-Dianping/lyrebird#724]
win10 ，部署完毕，启动后发现大量的kill请求，
![2022-12-13_120631](https://user-images.githubusercontent.com/1449374/207224224-66586944-8621-4e28-9a8c-31a8f5fa2ff0.jpg)

![2022-12-13_121030](https://user-images.githubusercontent.com/1449374/207224587-08489e21-992c-4f1c-bf78-27b5519006a4.jpg)

**Comment by zhaoye** [comment]
前后两个截图不是一个请求呀？
上图看起来是 http://127.0.0.1/kill
下图是 http://127.0.0.1/9090/api/status 吗？
@ohyeah521

**Comment by ohyeah521** [comment]
@zhaoye  是的，我允许2次，有的时候是kill,有的时候是api/status，很奇怪，可以屏蔽吗

**Comment by zhaoye** [comment]
这个请求应该不是Lyrebird自己发起的。可以参考这个来设置过滤 https://meituan-dianping.github.io/lyrebird/guide/config.html#proxy-filters

另外可以检查一下自己的环境，上面的截图看着是一段设置了代理的pyhon代码发起的请求。
@ohyeah521

**Comment by ohyeah521** [comment]
@zhaoye 查了一下代码，是我代码的问题，感谢回复。
