### ISSUE TITLE
保存数据包到文件 中

### ISSUE THREAD

**Issue by ohyeah521** [Meituan-Dianping/lyrebird#728]
把抓到的网络请求和应答数据输出到文件中

**Comment by zhaoye** [comment]
这是个需求吗？ 是说实时的保存成文件的意思？ @ohyeah521 可以详细一些吗

**Comment by ohyeah521** [comment]
@zhaoye 是个需求：把流量实时或定时保存到文件，方便自动化分析，不是人工看。
应用场景：大量app的自动化测试，发现可疑流量，自动预警。

**Comment by zhaoye** [comment]
这个场景不错呀. @ohyeah521 

实际上是有存储到文件的。大概有几个办法吧：
1. 数据是实时保存到sqlite里面的。 可以直接读~/.lyrebird/lyrebird.db
2. 也可以订阅消息总线，通过扩展的方式来触发其他功能。感觉这样比读DB更好一些。
> 详见 https://meituan-dianping.github.io/lyrebird/guide/checker.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%84%9A%E6%9C%AC

**Comment by ohyeah521** [comment]
@zhaoye 感谢解答，我研究一下
