### ISSUE TITLE
我这边windows启动报错，麻烦知道的大神可以帮忙指导一下为什么？

### ISSUE THREAD

**Issue by dreamshao** [Meituan-Dianping/lyrebird#730]
![image](https://user-images.githubusercontent.com/51390317/210057529-4b9dfd3f-aa64-487f-90b8-b413ffa7dd67.png)
报错原因：File "c:\\users\\15424\\appdata\\local\\programs\\python\\python37-32\\lib\\runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n', '  File "c:\\users\\15424\\appdata\\local\\programs\\python\\python37-32\\lib\\runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n', '  File "C:\\Users\\15424\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\lyrebird.exe\\__main__.py", line 7, in <module>\n    sys.exit(main())\n', '  File "c:\\users\\15424\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\lyrebird\\manager.py", line 151, in main\n    run(args)\n', '  File "c:\\users\\15424\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\lyrebird\\manager.py", line 188, in run\n    application.server[\'proxy\'] = LyrebirdProxyServer()\n', '  File "c:\\users\\15424\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\lyrebird\\mitm\\proxy_server.py", line 21, in __init__\n    self.mitm_path = init_mitm()\n', '  File "c:\\users\\15424\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\lyrebird\\mitm\\mitm_installer.py", line 101, in init_mitm\n    mitmdump_path = download_mitmproxy()\n', '  File "c:\\users\\15424\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\lyrebird\\mitm\\mitm_installer.py", line 85, in download_mitmproxy\n    tarf = tarfile.open(fileobj=tempf.file)\n', '  File "c:\\users\\15424\\appdata\\local\\programs\\python\\python37-32\\lib\\tarfile.py", line 1578, in open\n    raise ReadError("file could not be opened successfully")\n
报错代码截图：
![image](https://user-images.githubusercontent.com/51390317/210057757-b65b0bc1-4140-4728-9316-517858722c00.png)

**Comment by ohyeah521** [comment]
你的网络不好，在下载mitm的时候文件没下载成功，所以后面执行的时候崩溃了，你需要手动安装mitmproxy就可以了
`pip install mitmproxy`

**Comment by dreamshao** [comment]
> 你的网络不好，在下载mitm的时候文件没下载成功，所以后面执行的时候崩溃了，你需要手动安装mitmproxy就可以了 `pip install mitmproxy`

也没有成功

**Comment by ohyeah521** [comment]
> > 你的网络不好，在下载mitm的时候文件没下载成功，所以后面执行的时候崩溃了，你需要手动安装mitmproxy就可以了 `pip install mitmproxy`
> 
> 也没有成功

我掐指一算，你俩八字不合，换httptools试试吧

**Comment by zhaoye** [comment]
https://mitmproxy.org/
这里安装一下windows版本的mitmproxy吧。
<img width="834" alt="image" src="https://user-images.githubusercontent.com/4516926/210332379-90a82dff-d27a-4be9-acbf-659c872a286f.png">


然后再启动lyrebird。
@dreamshao

**Comment by dreamshao** [comment]
> https://mitmproxy.org/ 这里安装一下windows版本的mitmproxy吧。 <img alt="image" width="834" src="https://user-images.githubusercontent.com/4516926/210332379-90a82dff-d27a-4be9-acbf-659c872a286f.png">
> 
> 然后再启动lyrebird。 @dreamshao

  好的 我试试

**Comment by dreamshao** [comment]
> > > 你的网络不好，在下载mitm的时候文件没下载成功，所以后面执行的时候崩溃了，你需要手动安装mitmproxy就可以了 `pip install mitmproxy`
> > 
> > 
> > 也没有成功
> 
> 我掐指一算，你俩八字不合，换httptools试试吧

貌似今天可以了。。。。

**Comment by dreamshao** [comment]
> > https://mitmproxy.org/ 这里安装一下windows版本的mitmproxy吧。 <img alt="image" width="834" src="https://user-images.githubusercontent.com/4516926/210332379-90a82dff-d27a-4be9-acbf-659c872a286f.png">
> > 然后再启动lyrebird。 @dreamshao
> 
> 好的 我试试

已经可以了 多谢
