### ISSUE TITLE
Buglt 插件报错：AttributeError: 'ConfigManager' object has no attribute 'root'

### ISSUE THREAD

**Issue by YQBaobao** [Meituan-Dianping/lyrebird#762]
**Description**
打开Buglt插件页面时，页面报错：AttributeError: 'ConfigManager' object has no attribute 'root'

**To Reproduce**
1. setup 'Buglt'，版本为最新的：1.12.1
2. Click on 'Buglt'
3. See error：AttributeError: 'ConfigManager' object has no attribute 'root'

**Expected behavior**
正确的打开页面，不报任何错误

**Screenshots**
![image](https://github.com/Meituan-Dianping/lyrebird/assets/50287870/84c1358e-52f2-476b-9b73-993a12b9c602)

**Desktop (please complete the following information):**
与此无关

**Smartphone (please complete the following information):**
与此无关

**Additional context**
第一次接触这个软件，但是看到报错是无属性，于是看了下源码，ConfigManager类的属性中并无root，而是ROOT，于是修改如下：
ROOT = application._cm.ROOT
重启lyrebird，进入Buglt页，不报错

**Comment by yumiguan** [comment]
Fix in https://github.com/Meituan-Dianping/lyrebird-bugit/pull/46
