### ISSUE TITLE
想要修改请求参数可以支持吗

### ISSUE THREAD

**Issue by suqingyue738** [Meituan-Dianping/lyrebird#80]
想要修改请求参数可以支持吗？
目前有计划加入自动化测试，但是只能修改响应参数，不能修改请求参数

**Comment by zhaoye** [comment]
目前暂时不支持修改请求再重新发出。
请问这样的功能是怎样进行自动化的呢? 如果是测试服务端的话不如直接跑接口测试了吧。
@suqingyue738
